/**
 * Bid Wars content catalog: big categories, each with several subtopics.
 * A round draws 10 items from one subtopic. Items are never shown before they are up for auction.
 * Each subtopic needs at least 10 items; most carry 14–20 so rounds differ.
 */
export type SubtopicDef = { id: string; title: string; subtitle: string; items: string[] };
export type CategoryDef = { id: string; title: string; subtitle: string; accent: string; subtopics: SubtopicDef[] };

const cat = (id: string, title: string, subtitle: string, accent: string, subtopics: SubtopicDef[]): CategoryDef => ({ id, title, subtitle, accent, subtopics });
const sub = (id: string, title: string, subtitle: string, items: string[]): SubtopicDef => ({ id, title, subtitle, items });

export const CATALOG: CategoryDef[] = [
  cat('valorant', 'Valorant', 'Skins, agents, maps, pros', '#E84A55', [
    sub('valorant-vandals', 'Vandal Skins', 'One Vandal for life', ['Prime Vandal', 'Reaver Vandal', 'Elderflame Vandal', 'Champions 2021 Vandal', 'Oni Vandal', 'Glitchpop Vandal', "Gaia's Vengeance Vandal", 'Kuronami Vandal', 'Araxys Vandal', 'RGX 11z Pro Vandal', 'Sentinels of Light Vandal', 'Forsaken Vandal', 'Prelude to Chaos Vandal', 'Ion Vandal', 'Neo Frontier Vandal', 'Magepunk Vandal', 'Spectrum Vandal', 'Evori Dreamwings Vandal', 'Mystbloom Vandal', 'Chronovoid Vandal']),
    sub('valorant-phantoms', 'Phantom Skins', 'The other rifle', ['Oni Phantom', 'Ion Phantom', 'Spectrum Phantom', 'Glitchpop Phantom', 'RGX 11z Pro Phantom', 'Recon Phantom', 'Prime Phantom', 'Reaver Phantom', 'Nunca Olvidados Phantom', 'Singularity Phantom', 'Radiant Entertainment System Phantom', 'Kuronami Phantom', 'Champions 2023 Phantom', 'Neptune Phantom', 'Xenohunter Phantom', 'BlastX Phantom']),
    sub('valorant-knives', 'Knife Skins', 'Show off between rounds', ['Reaver Karambit', 'Prime Karambit', 'Sovereign Sword', 'Elderflame Dagger', 'Glitchpop Dagger', 'RGX 11z Pro Blade', 'Champions 2021 Karambit', 'Oni Claw', 'Prime 2.0 Axe', 'Ion Karambit', 'Recon Balisong', 'Kuronami Wakizashi', 'Araxys Bio Harvester', 'Magepunk Electroblade', 'Spectrum Waveform', 'Sentinels of Light Blade', 'Ruination Blade', 'Singularity Knife', 'Neo Frontier Axe', 'Chronovoid Blade']),
    sub('valorant-agents', 'Agents', 'Your main, forever', ['Jett', 'Reyna', 'Raze', 'Phoenix', 'Sage', 'Sova', 'Omen', 'Cypher', 'Killjoy', 'Viper', 'Brimstone', 'Breach', 'Skye', 'Yoru', 'Astra', 'KAY/O', 'Chamber', 'Neon', 'Fade', 'Harbor', 'Gekko', 'Deadlock', 'Iso', 'Clove', 'Vyse', 'Tejo', 'Waylay']),
    sub('valorant-maps', 'Maps', 'Pick your battleground', ['Ascent', 'Bind', 'Haven', 'Split', 'Icebox', 'Breeze', 'Fracture', 'Pearl', 'Lotus', 'Sunset', 'Abyss', 'Corrode']),
    sub('valorant-pros', 'Pro Players', 'Sign one to your roster', ['TenZ', 'aspas', 'Demon1', 'Derke', 'yay', 'ScreaM', 'Boaster', 'f0rsakeN', 'Something', 'cNed', 'Chronicle', 'Alfajer', 'Sacy', 'Less', 'Zekken', 'Leo', 'Jinggg', 'Cryocells', 'Ethan', 'Shao']),
    sub('valorant-teams', 'Pro Teams', 'Buy the org', ['Fnatic', 'Sentinels', 'LOUD', 'Paper Rex', 'Team Liquid', 'Evil Geniuses', 'DRX', 'NRG', '100 Thieves', 'Gen.G', 'Team Heretics', 'Cloud9', 'KRÜ Esports', 'FUT Esports', 'Karmine Corp', 'G2 Esports', 'Team Vitality', 'Leviatán']),
  ]),
  cat('cs2', 'Counter-Strike', 'Knives, skins, maps, legends', '#F5A623', [
    sub('cs2-knives', 'Knife Types', 'The flex in the loadout', ['Karambit', 'M9 Bayonet', 'Butterfly Knife', 'Bayonet', 'Flip Knife', 'Gut Knife', 'Huntsman Knife', 'Falchion Knife', 'Shadow Daggers', 'Bowie Knife', 'Ursus Knife', 'Navaja Knife', 'Stiletto Knife', 'Talon Knife', 'Skeleton Knife', 'Nomad Knife', 'Paracord Knife', 'Survival Knife', 'Classic Knife', 'Kukri Knife']),
    sub('cs2-ak', 'AK-47 Skins', 'The rifle that matters', ['Fire Serpent', 'Wild Lotus', 'Case Hardened', 'Asiimov', 'Vulcan', 'Redline', 'Bloodsport', 'Neon Rider', 'Fuel Injector', 'Jaguar', 'Aquamarine Revenge', 'The Empress', 'Inheritance', 'Nightwish', 'Head Shot', 'Legion of Anubis', 'Gold Arabesque', 'X-Ray', 'Slate', 'Ice Coaled']),
    sub('cs2-awp', 'AWP Skins', 'One shot, one flex', ['Dragon Lore', 'Medusa', 'Gungnir', 'Asiimov', 'Lightning Strike', 'Hyper Beast', 'Neo-Noir', 'Wildfire', 'Containment Breach', 'Fade', 'Chromatic Aberration', 'Desert Hydra', 'The Prince', 'Oni Taiji', 'BOOM', 'Duality', 'Chrome Cannon', 'Atheris', 'Electric Hive', 'Man-o\'-war']),
    sub('cs2-maps', 'Maps', 'Where you grind', ['Dust II', 'Mirage', 'Inferno', 'Nuke', 'Overpass', 'Ancient', 'Anubis', 'Vertigo', 'Train', 'Cache', 'Cobblestone', 'Office', 'Italy', 'Aztec']),
    sub('cs2-legends', 'Legends', 'Sign a GOAT', ['s1mple', 'ZywOo', 'NiKo', 'device', 'coldzera', 'olofmeister', 'GeT_RiGhT', 'f0rest', 'kennyS', 'donk', 'm0NESY', 'ropz', 'electronic', 'FalleN', 'Twistzz', 'EliGE', 'karrigan', 'sh1ro', 'Ax1Le', 'b1t']),
  ]),
  cat('league', 'League of Legends', 'Champions, roles, legends', '#4FC3F7', [
    sub('league-champs', 'Champions', 'Lock in forever', ['Yasuo', 'Zed', 'Ahri', 'Lee Sin', 'Jinx', 'Thresh', 'Ezreal', 'Lux', 'Katarina', 'Darius', 'Vayne', 'Riven', 'Akali', 'Kai\'Sa', 'Garen', 'Teemo', 'Yone', 'Sett', 'Viego', 'Samira', 'Zeri', 'Aphelios', 'Lucian', 'Irelia']),
    sub('league-skins', 'Skin Lines', 'Cosmetics, forever', ['PROJECT', 'K/DA', 'Star Guardian', 'Spirit Blossom', 'High Noon', 'Arcane', 'Elderwood', 'Pulsefire', 'God-King', 'Battle Academia', 'Blood Moon', 'Odyssey', 'Coven', 'Dark Star', 'Mecha', 'Space Groove', 'Empyrean', 'Heartsteel', 'True Damage', 'Dragonmancer']),
    sub('league-pros', 'Pro Players', 'Build your super team', ['Faker', 'Chovy', 'Caps', 'Ruler', 'Zeus', 'Canyon', 'Keria', 'Oner', 'Gumayusi', 'Knight', 'Bin', 'Showmaker', 'Deft', 'Peanut', 'Rekkles', 'Uzi', 'TheShy', 'Doinb', 'Rookie', 'Jankos']),
  ]),
  cat('fortnite', 'Fortnite', 'Skins, POIs, chapters', '#B27BE6', [
    sub('fortnite-skins', 'Skins', 'One skin, all season', ['Renegade Raider', 'Black Knight', 'Skull Trooper', 'Ghoul Trooper', 'Peely', 'Fishstick', 'Midas', 'Drift', 'Raven', 'Galaxy', 'Aerial Assault Trooper', 'Ikonik', 'Travis Scott', 'John Wick', 'Omega', 'Meowscles', 'Jonesy', 'Lynx', 'Marshmello', 'The Reaper', 'Ariana Grande', 'Goku', 'Spider-Man', 'Darth Vader']),
    sub('fortnite-pois', 'Landing Spots', 'Where you drop', ['Tilted Towers', 'Retail Row', 'Pleasant Park', 'Salty Springs', 'Dusty Depot', 'Loot Lake', 'Lazy Lagoon', 'Paradise Palms', 'Lucky Landing', 'Greasy Grove', 'Wailing Woods', 'The Agency', 'Mega City', 'Sweaty Sands', 'Coral Castle', 'Craggy Cliffs']),
    sub('fortnite-collabs', 'Collabs', 'Crossovers that broke the game', ['Marvel', 'Star Wars', 'Dragon Ball', 'Naruto', 'Travis Scott concert', 'Eminem concert', 'Ariana Grande concert', 'DC', 'Attack on Titan', 'Jujutsu Kaisen', 'LEGO', 'Nike', 'Balenciaga', 'Halo', 'God of War', 'The Witcher']),
  ]),
  cat('minecraft', 'Minecraft', 'Blocks, mobs, biomes', '#6BBF59', [
    sub('minecraft-mobs', 'Mobs', 'Keep one as a pet', ['Creeper', 'Enderman', 'Wolf', 'Axolotl', 'Allay', 'Warden', 'Ender Dragon', 'Wither', 'Villager', 'Iron Golem', 'Piglin', 'Ghast', 'Phantom', 'Bee', 'Fox', 'Panda', 'Sniffer', 'Camel', 'Frog', 'Skeleton']),
    sub('minecraft-biomes', 'Biomes', 'Where you build your base', ['Cherry Grove', 'Deep Dark', 'Lush Caves', 'Jungle', 'Mushroom Fields', 'Ice Spikes', 'Badlands', 'Mangrove Swamp', 'Savanna', 'Dark Forest', 'Taiga', 'Desert', 'Plains', 'Ocean Monument', 'Nether Wastes', 'Basalt Deltas', 'The End', 'Pale Garden']),
    sub('minecraft-blocks', 'Blocks & Items', 'Unlimited supply of one', ['Diamond', 'Netherite', 'Elytra', 'Totem of Undying', 'Enchanted Golden Apple', 'Beacon', 'Shulker Box', 'Trident', 'Mace', 'Ancient Debris', 'Nether Star', 'Dragon Egg', 'Sponge', 'Obsidian', 'TNT', 'Ender Pearl']),
  ]),
  cat('games', 'Video Games', 'Franchises and consoles', '#B27BE6', [
    sub('games-forever', 'One Game Forever', 'Only game you can play', ['GTA V', 'Minecraft', 'EA FC', 'Call of Duty', 'Red Dead Redemption 2', 'Fortnite', 'Rocket League', 'Mario Kart', 'Elden Ring', 'Valorant', 'Zelda: Breath of the Wild', 'The Witcher 3', 'God of War', 'Cyberpunk 2077', 'Baldur\'s Gate 3', 'Overwatch', 'Apex Legends', 'Among Us', 'Roblox', 'Clash Royale']),
    sub('games-consoles', 'Consoles', 'One console, no PC', ['PlayStation 5', 'Xbox Series X', 'Nintendo Switch 2', 'Steam Deck', 'PlayStation 2', 'Nintendo 64', 'Game Boy', 'PSP', 'Xbox 360', 'Wii', 'Dreamcast', 'GameCube', 'PlayStation Portal', 'ROG Ally', 'PS Vita', 'SNES']),
    sub('games-characters', 'Characters', 'Bring one to life', ['Mario', 'Master Chief', 'Kratos', 'Link', 'Lara Croft', 'Geralt', 'Sonic', 'Pikachu', 'Solid Snake', 'Arthur Morgan', 'Ellie', 'Joel', 'Cloud Strife', 'Samus', 'Pac-Man', 'Doom Slayer', 'Nathan Drake', 'Kirby', 'Trevor Philips', 'Sephiroth']),
    sub('games-mobile', 'Mobile Games', 'Phone game for life', ['Clash of Clans', 'Clash Royale', 'Brawl Stars', 'PUBG Mobile', 'Free Fire', 'Candy Crush', 'Subway Surfers', 'Pokémon GO', 'Genshin Impact', 'Among Us', 'Roblox', 'Call of Duty Mobile', 'Ludo Star', 'Jackaroo', 'Baloot', 'Monopoly GO', 'Stumble Guys', '8 Ball Pool']),
    sub('games-roblox', 'Roblox Games', 'Only one experience forever', ['Blox Fruits', 'Adopt Me!', 'Brookhaven', 'Grow a Garden', 'Dress to Impress', 'Murder Mystery 2', 'Tower of Hell', 'Pet Simulator 99', 'Doors', 'Arsenal', 'Jailbreak', 'Bedwars', 'Rivals', 'Fisch', 'The Strongest Battlegrounds', 'Steal a Brainrot', 'Bee Swarm Simulator', 'Piggy', 'Natural Disaster Survival', 'Work at a Pizza Place']),
    sub('games-pokemon', 'Pokémon', 'One partner for the journey', ['Pikachu', 'Charizard', 'Mewtwo', 'Gengar', 'Lucario', 'Greninja', 'Eevee', 'Snorlax', 'Rayquaza', 'Garchomp', 'Blastoise', 'Dragonite', 'Umbreon', 'Gardevoir', 'Arceus', 'Mew', 'Lugia', 'Tyranitar', 'Squirtle', 'Bulbasaur']),
    sub('games-fifa-icons', 'EA FC Icons', 'Your ultimate team', ['Pelé', 'Maradona', 'Ronaldinho', 'Zidane', 'Ronaldo Nazário', 'Thierry Henry', 'Gullit', 'Eusébio', 'Cruyff', 'Beckenbauer', 'Maldini', 'Cantona', 'Van Basten', 'Garrincha', 'Dennis Bergkamp', 'Kaká', 'Gerrard', 'Lampard', 'Drogba', 'Puskás']),
  ]),
  cat('football', 'Football', 'Players, clubs, kits, moments', '#4FC677', [
    sub('football-players', 'Players', 'Sign one, lose the other', ['Lionel Messi', 'Cristiano Ronaldo', 'Kylian Mbappé', 'Erling Haaland', 'Mohamed Salah', 'Neymar', 'Jude Bellingham', 'Vinícius Jr.', 'Kevin De Bruyne', 'Rodri', 'Lamine Yamal', 'Bukayo Saka', 'Harry Kane', 'Karim Benzema', 'Luka Modrić', 'Pedri', 'Florian Wirtz', 'Cole Palmer', 'Ousmane Dembélé', 'Achraf Hakimi']),
    sub('football-legends', 'Legends', 'Prime version, one season', ['Pelé', 'Diego Maradona', 'Zinedine Zidane', 'Ronaldinho', 'Ronaldo Nazário', 'Thierry Henry', 'Johan Cruyff', 'Paolo Maldini', 'Andrés Iniesta', 'Xavi', 'Steven Gerrard', 'Frank Lampard', 'Kaká', 'Roberto Carlos', 'Andrea Pirlo', 'Didier Drogba', 'Wayne Rooney', 'Francesco Totti', 'Alessandro Del Piero', 'Iker Casillas']),
    sub('football-clubs', 'Clubs', 'Own one club', ['Real Madrid', 'Barcelona', 'Manchester United', 'Manchester City', 'Liverpool', 'Arsenal', 'Chelsea', 'Bayern Munich', 'PSG', 'Juventus', 'AC Milan', 'Inter', 'Borussia Dortmund', 'Atlético Madrid', 'Tottenham', 'Ajax', 'Napoli', 'Benfica', 'Al Hilal', 'Al Nassr']),
    sub('football-spl', 'Saudi Pro League Stars', 'Roshn League signings', ['Cristiano Ronaldo', 'Karim Benzema', 'Sadio Mané', 'Riyad Mahrez', 'Salem Al-Dawsari', 'Aleksandar Mitrović', 'N\'Golo Kanté', 'Ivan Toney', 'João Félix', 'Kingsley Coman', 'Theo Hernández', 'Darwin Núñez', 'Rúben Neves', 'Aymeric Laporte', 'Roberto Firmino', 'Fabinho', 'Marcelo Brozović', 'Moussa Diaby', 'Jhon Durán', 'Enzo Millot']),
    sub('football-saudi-clubs', 'Saudi Clubs', 'Pick your side', ['Al Hilal', 'Al Nassr', 'Al Ittihad', 'Al Ahli', 'Al Shabab', 'Al Ettifaq', 'Al Taawoun', 'Al Fateh', 'Al Raed', 'Damac', 'Al Khaleej', 'Al Fayha', 'Al Riyadh', 'Al Wehda', 'Al Okhdood', 'Al Qadsiah', 'Al Kholood', 'Al Orobah', 'Neom SC', 'Al Najma']),
    sub('football-stadiums', 'Stadiums', 'Season ticket for life', ['Camp Nou', 'Santiago Bernabéu', 'Old Trafford', 'Anfield', 'Allianz Arena', 'San Siro', 'Wembley', 'Signal Iduna Park', 'Emirates Stadium', 'Etihad Stadium', 'Parc des Princes', 'Maracanã', 'La Bombonera', 'Kingdom Arena', 'King Abdullah Sports City', 'Lusail Stadium', 'Estadio Azteca', 'Stamford Bridge']),
    sub('football-kits', 'Iconic Kits', 'Wear one forever', ['Nigeria 2018 home', 'Barcelona 1999 centenary', 'Man United 1999 home', 'Real Madrid 2002 home', 'Arsenal 2005 redcurrant', 'Juventus 1996 home', 'AC Milan 2007 home', 'Brazil 2002 home', 'Argentina 1986 home', 'Netherlands 1988 home', 'Germany 1990 home', 'Liverpool 2005 home', 'Inter 2010 home', 'PSG 2021 Jordan', 'Al Hilal 2023 home', 'Saudi Arabia 2022 home', 'Chelsea 2012 home', 'Ajax 1995 home']),
  ]),
  cat('sports', 'Sports', 'Basketball, F1, fighters', '#FF8C42', [
    sub('sports-nba', 'NBA Players', 'Build your franchise', ['LeBron James', 'Stephen Curry', 'Kevin Durant', 'Giannis Antetokounmpo', 'Nikola Jokić', 'Luka Dončić', 'Jayson Tatum', 'Shai Gilgeous-Alexander', 'Victor Wembanyama', 'Anthony Edwards', 'Joel Embiid', 'Ja Morant', 'Kyrie Irving', 'Devin Booker', 'Jimmy Butler', 'Damian Lillard', 'Kawhi Leonard', 'Jalen Brunson', 'Tyrese Haliburton', 'Zion Williamson']),
    sub('sports-nba-legends', 'NBA Legends', 'Prime version, one season', ['Michael Jordan', 'Kobe Bryant', 'Shaquille O\'Neal', 'Magic Johnson', 'Larry Bird', 'Kareem Abdul-Jabbar', 'Tim Duncan', 'Hakeem Olajuwon', 'Allen Iverson', 'Dirk Nowitzki', 'Wilt Chamberlain', 'Bill Russell', 'Dwyane Wade', 'Vince Carter', 'Tracy McGrady', 'Steve Nash', 'Kevin Garnett', 'Charles Barkley']),
    sub('sports-f1-drivers', 'F1 Drivers', 'Your number one seat', ['Max Verstappen', 'Lewis Hamilton', 'Charles Leclerc', 'Lando Norris', 'Oscar Piastri', 'George Russell', 'Carlos Sainz', 'Fernando Alonso', 'Kimi Antonelli', 'Yuki Tsunoda', 'Pierre Gasly', 'Alex Albon', 'Oliver Bearman', 'Nico Hülkenberg', 'Lance Stroll', 'Esteban Ocon', 'Isack Hadjar', 'Gabriel Bortoleto', 'Liam Lawson', 'Franco Colapinto']),
    sub('sports-f1-legends', 'F1 Legends', 'Prime version, one season', ['Ayrton Senna', 'Michael Schumacher', 'Alain Prost', 'Niki Lauda', 'Sebastian Vettel', 'Kimi Räikkönen', 'Mika Häkkinen', 'Juan Manuel Fangio', 'Jim Clark', 'Nigel Mansell', 'Nelson Piquet', 'Jackie Stewart', 'Gilles Villeneuve', 'Jenson Button', 'Daniel Ricciardo', 'Nico Rosberg']),
    sub('sports-f1-teams', 'F1 Teams', 'Own the garage', ['Ferrari', 'Red Bull', 'McLaren', 'Mercedes', 'Aston Martin', 'Williams', 'Alpine', 'Haas', 'Racing Bulls', 'Sauber / Audi', 'Cadillac', 'Lotus', 'Brabham', 'Benetton']),
    sub('sports-f1-circuits', 'F1 Circuits', 'Race there every year', ['Monaco', 'Spa-Francorchamps', 'Silverstone', 'Suzuka', 'Monza', 'Jeddah Corniche', 'Yas Marina', 'Bahrain', 'Interlagos', 'Singapore', 'Las Vegas', 'Miami', 'Austin', 'Zandvoort', 'Imola', 'Hungaroring', 'Baku', 'Qiddiya']),
    sub('sports-ufc', 'UFC Fighters', 'Corner one fighter', ['Islam Makhachev', 'Jon Jones', 'Alex Pereira', 'Ilia Topuria', 'Khabib Nurmagomedov', 'Conor McGregor', 'Israel Adesanya', 'Dricus du Plessis', 'Tom Aspinall', 'Charles Oliveira', 'Max Holloway', 'Sean O\'Malley', 'Merab Dvalishvili', 'Belal Muhammad', 'Alexander Volkanovski', 'Anderson Silva', 'Georges St-Pierre', 'Jorge Masvidal', 'Nate Diaz', 'Khamzat Chimaev']),
    sub('sports-wwe', 'WWE Superstars', 'Your walkout music, their entrance', ['The Rock', 'John Cena', 'Roman Reigns', 'Cody Rhodes', 'Stone Cold Steve Austin', 'The Undertaker', 'Randy Orton', 'Seth Rollins', 'CM Punk', 'Rey Mysterio', 'Brock Lesnar', 'Triple H', 'Shawn Michaels', 'Rhea Ripley', 'Becky Lynch', 'Jey Uso', 'Gunther', 'Logan Paul', 'Kane', 'Eddie Guerrero']),
    sub('sports-tennis', 'Tennis & Padel', 'Court for life', ['Carlos Alcaraz', 'Jannik Sinner', 'Novak Djokovic', 'Rafael Nadal', 'Roger Federer', 'Serena Williams', 'Iga Świątek', 'Coco Gauff', 'Aryna Sabalenka', 'Andy Murray', 'Alexander Zverev', 'Daniil Medvedev', 'Naomi Osaka', 'Pete Sampras', 'Andre Agassi', 'Juan Lebrón', 'Ale Galán', 'Arturo Coello', 'Agustín Tapia', 'Paquito Navarro']),
    sub('sports-boxers', 'Boxers', 'All-time and now', ['Muhammad Ali', 'Mike Tyson', 'Floyd Mayweather', 'Manny Pacquiao', 'Canelo Álvarez', 'Tyson Fury', 'Oleksandr Usyk', 'Anthony Joshua', 'Terence Crawford', 'Naoya Inoue', 'Sugar Ray Leonard', 'Lennox Lewis', 'Evander Holyfield', 'Rocky Marciano', 'Deontay Wilder', 'Gervonta Davis']),
  ]),
  cat('cars', 'Cars', 'Dream garages of every kind', '#A9C1DE', [
    sub('cars-dream', 'Dream Cars', 'Keys to anything', ['Porsche 911 GT3', 'Ferrari 296 GTB', 'Lamborghini Revuelto', 'Mercedes-AMG G63', 'BMW M5', 'Audi RS6', 'Toyota Land Cruiser', 'McLaren 750S', 'Range Rover SV', 'Mazda MX-5', 'Rolls-Royce Cullinan', 'Bentley Continental GT', 'Aston Martin DB12', 'Nissan GT-R', 'Ford Mustang GTD', 'Tesla Model S Plaid', 'Porsche Taycan', 'Lexus LX 600']),
    sub('cars-hyper', 'Hypercars', 'Seven figures, one seat', ['Bugatti Chiron', 'Koenigsegg Jesko', 'Rimac Nevera', 'Pagani Huayra', 'McLaren F1', 'Ferrari LaFerrari', 'Porsche 918 Spyder', 'McLaren P1', 'Aston Martin Valkyrie', 'Mercedes-AMG One', 'Bugatti Tourbillon', 'Koenigsegg Gemera', 'Lamborghini Sián', 'Ferrari F80', 'Gordon Murray T.50', 'Hennessey Venom F5']),
    sub('cars-jdm', 'JDM Legends', 'Tuner heaven', ['Nissan Skyline GT-R R34', 'Toyota Supra MK4', 'Honda NSX', 'Mazda RX-7', 'Mitsubishi Lancer Evo IX', 'Subaru Impreza WRX STI', 'Nissan Silvia S15', 'Honda Civic Type R EK9', 'Toyota AE86', 'Nissan 350Z', 'Lexus LFA', 'Acura Integra Type R', 'Toyota Chaser', 'Mazda Miata NA', 'Nissan 240SX', 'Honda S2000']),
    sub('cars-suvs', 'SUVs', 'The family flagship', ['Toyota Land Cruiser', 'Nissan Patrol', 'Mercedes G-Class', 'Range Rover', 'Lexus LX', 'Cadillac Escalade', 'GMC Yukon Denali', 'Chevrolet Tahoe', 'Lamborghini Urus', 'Porsche Cayenne', 'BMW X7', 'Toyota FJ Cruiser', 'Ford Bronco', 'Jeep Wrangler', 'Rolls-Royce Cullinan', 'Bentley Bentayga', 'Land Rover Defender', 'Toyota Fortuner']),
    sub('cars-classics', 'Classics', 'Sunday drive for life', ['Ford Mustang 1967', 'Chevrolet Camaro 1969', 'Porsche 911 (930 Turbo)', 'Mercedes 300SL Gullwing', 'Jaguar E-Type', 'Ferrari 250 GTO', 'Lamborghini Countach', 'Ferrari Testarossa', 'DeLorean DMC-12', 'BMW E30 M3', 'Dodge Charger 1969', 'Land Rover Series', 'Mercedes 560 SEC', 'Toyota Land Cruiser FJ40', 'Chevrolet Caprice 1990', 'Ford GT40']),
    sub('cars-brands', 'Car Brands', 'Own the whole company', ['Toyota', 'Mercedes-Benz', 'BMW', 'Porsche', 'Ferrari', 'Lamborghini', 'Tesla', 'Nissan', 'Lexus', 'Audi', 'Rolls-Royce', 'Bentley', 'Ford', 'Chevrolet', 'Hyundai', 'Kia', 'McLaren', 'Aston Martin', 'Bugatti', 'BYD']),
  ]),
  cat('food', 'Food', 'Comfort, chains, sweets, drinks', '#F0703E', [
    sub('food-comfort', 'Comfort Food', 'Comfort classics and wildcards', ['Pizza', 'Cheeseburger', 'Tacos', 'Chicken Wings', 'Sushi', 'Spaghetti', 'Fried Chicken', 'Steak', 'Ramen', 'Escargot', 'Biryani', 'Lasagna', 'Butter Chicken', 'Pad Thai', 'Fish and Chips', 'Shawarma', 'Dumplings', 'Mac and Cheese', 'Pho', 'Falafel']),
    sub('food-fastfood', 'Fast Food Chains', 'Pick your drive-thru', ["McDonald's", 'KFC', "Raising Cane's", 'Five Guys', 'Shake Shack', 'Popeyes', 'Burger King', 'Taco Bell', "Wendy's", 'Subway', 'Chick-fil-A', 'In-N-Out', 'Domino\'s', 'Pizza Hut', 'Hardee\'s', 'Texas Chicken', 'Dunkin\'', 'Starbucks', 'Little Caesars', 'Papa John\'s']),
    sub('food-saudi-chains', 'Saudi Chains', 'Only one for the rest of your life', ['Al Baik', 'Kudu', 'Herfy', 'Shawarmer', 'Al Tazaj', 'Maestro Pizza', 'Hamburgini', 'Section-B', 'Barn\'s', 'Half Million', 'Dr. Café', 'Al Romansiah', 'Mama Noura', 'Bateel', 'Munch Bakery', 'Salt', 'Burgerizzr', 'Fakieh', 'Meat Moot', 'Steak House']),
    sub('food-saudi-dishes', 'Saudi Dishes', 'Home cooking, forever', ['Kabsa', 'Mandi', 'Jareesh', 'Saleeg', 'Mutabbaq', 'Harees', 'Margoog', 'Matazeez', 'Qursan', 'Hininy', 'Kleija', 'Masoub', 'Foul', 'Tamees', 'Mathlotha', 'Samboosa', 'Luqaimat', 'Aseeda', 'Madfoon', 'Haneeth']),
    sub('food-desserts', 'Desserts', 'Sweet tooth for life', ['Kunafa', 'Cheesecake', 'Tiramisu', 'Baklava', 'Umm Ali', 'Luqaimat', 'Brownies', 'Molten Cake', 'Ice Cream', 'Crème Brûlée', 'Macarons', 'Churros', 'Waffles', 'Donuts', 'Basbousa', 'Pavlova', 'Cinnamon Rolls', 'Mochi', 'Gelato', 'Dubai Chocolate']),
    sub('food-drinks', 'Drinks', 'The only thing you drink', ['Coffee', 'Karak', 'Saudi Coffee', 'Matcha', 'Bubble Tea', 'Coca-Cola', 'Pepsi', 'Red Bull', 'Monster', 'Vimto', 'Rani', 'Sun Top', 'Al Rabie Juice', 'Laban', 'Sparkling Water', 'Lemonade', 'Iced Latte', 'Spanish Latte', 'Hot Chocolate', 'Sobia']),
    sub('food-gulf-snacks', 'Gulf Childhood Snacks', 'The baqala classics', ['Chips Oman', 'Tang', 'Kinder Bueno', 'Galaxy', 'Mackintosh\'s', 'Pofaki', 'Kitco Chips', 'Oreo', 'Loacker', 'Kit Kat', 'Snickers', 'Barni', 'Nutella', 'Bounty', 'Ring Pop', 'Cerelac', 'Digestive', 'Tiger Chips', 'Indomie', 'Maggi']),
    sub('food-coffee', 'Coffee Orders', 'Your order, every morning', ['Spanish latte', 'Flat white', 'Iced americano', 'V60 pour-over', 'Cortado', 'Saudi coffee with dates', 'Karak', 'Cold brew', 'Pistachio latte', 'Caramel macchiato', 'Matcha latte', 'Espresso shot', 'Turkish coffee', 'Frappuccino', 'Cappuccino', 'Mocha', 'Affogato', 'Dirty chai']),
    sub('food-cuisines', 'Cuisines', 'One cuisine, every meal', ['Italian', 'Japanese', 'Mexican', 'Indian', 'Lebanese', 'Saudi', 'Thai', 'Chinese', 'Turkish', 'Korean', 'American', 'French', 'Greek', 'Yemeni', 'Egyptian', 'Vietnamese', 'Moroccan', 'Persian']),
  ]),
  cat('travel', 'Travel', 'Countries, cities, escapes', '#6FBFE8', [
    sub('travel-countries', 'Countries', 'Where are you flying?', ['Japan', 'Italy', 'Maldives', 'Switzerland', 'United States', 'Thailand', 'Iceland', 'Greece', 'Spain', 'South Korea', 'Türkiye', 'France', 'Egypt', 'Morocco', 'Indonesia', 'Georgia', 'Bosnia', 'Azerbaijan', 'United Kingdom', 'Australia']),
    sub('travel-cities', 'Cities', 'Live there a year', ['Tokyo', 'Paris', 'London', 'New York', 'Dubai', 'Istanbul', 'Rome', 'Barcelona', 'Seoul', 'Bangkok', 'Los Angeles', 'Riyadh', 'Cairo', 'Kuala Lumpur', 'Singapore', 'Amsterdam', 'Lisbon', 'Doha', 'Bali', 'Miami']),
    sub('travel-saudi-cities', 'Saudi Cities', 'Move there tomorrow', ['Riyadh', 'Jeddah', 'Makkah', 'Madinah', 'Dammam', 'Khobar', 'Abha', 'Taif', 'AlUla', 'Tabuk', 'Hail', 'Jazan', 'Najran', 'Al Baha', 'Buraidah', 'Yanbu', 'Dhahran', 'Al Ahsa', 'Neom', 'Diriyah']),
    sub('travel-riyadh', 'Riyadh Spots', 'Your weekend, every weekend', ['Boulevard City', 'Kingdom Centre', 'Al Faisaliah', 'Diriyah Bujairi', 'Riyadh Front', 'Al Nakheel Mall', 'Granada Mall', 'U Walk', 'Riyadh Park', 'VIA Riyadh', 'Kingdom Arena', 'Wadi Hanifa', 'Edge of the World', 'Riyadh Zoo', 'King Fahd Stadium', 'Boulevard World', 'Al Masmak', 'Salam Park', 'Riyadh Season', 'Suwaidi Park']),
    sub('travel-islands', 'Islands', 'Private island vibes', ['Maldives', 'Bali', 'Santorini', 'Bora Bora', 'Phuket', 'Sardinia', 'Zanzibar', 'Seychelles', 'Mauritius', 'Ibiza', 'Capri', 'Hawaii', 'Mykonos', 'Sinalah', 'Farasan', 'Langkawi']),
    sub('travel-experiences', 'Bucket List', 'One trip, all expenses paid', ['Northern Lights', 'Safari in Kenya', 'Cherry blossoms in Japan', 'Hajj', 'Skydiving in Dubai', 'Machu Picchu', 'Route 66 road trip', 'Cruise in Norway', 'Ski in the Alps', 'Champions League final', 'Super Bowl', 'F1 Monaco', 'World Cup final', 'Coachella', 'Everest base camp', 'Riyadh Season']),
  ]),
  cat('anime', 'Anime', 'Series, heroes, villains', '#FF5C8A', [
    sub('anime-series', 'Series', 'Only one show forever', ['One Piece', 'Naruto', 'Attack on Titan', 'Dragon Ball Z', 'Demon Slayer', 'Jujutsu Kaisen', 'Death Note', 'Fullmetal Alchemist', 'Hunter x Hunter', 'My Hero Academia', 'Bleach', 'Chainsaw Man', 'Solo Leveling', 'Haikyuu!!', 'Spy x Family', 'Vinland Saga', 'Cowboy Bebop', 'One Punch Man', 'Tokyo Ghoul', 'Blue Lock']),
    sub('anime-heroes', 'Heroes', 'Be them for a week', ['Luffy', 'Naruto', 'Goku', 'Levi', 'Tanjiro', 'Gojo', 'Light Yagami', 'Edward Elric', 'Gon', 'Deku', 'Ichigo', 'Saitama', 'Eren', 'Zoro', 'Killua', 'Itachi', 'Vegeta', 'Kakashi', 'Sung Jinwoo', 'Denji']),
    sub('anime-villains', 'Villains', 'Best antagonist', ['Madara', 'Aizen', 'Frieza', 'Sukuna', 'Muzan', 'Meruem', 'Dio', 'All For One', 'Griffith', 'Doflamingo', 'Pain', 'Cell', 'Hisoka', 'Zeke', 'Kaido', 'Orochimaru', 'Shigaraki', 'Blackbeard']),
  ]),
  cat('screen', 'TV & Movies', 'Shows, films, universes', '#F5C451', [
    sub('screen-shows', 'TV Shows', 'Rewatch forever', ['Breaking Bad', 'Game of Thrones', 'The Office', 'Friends', 'Stranger Things', 'Prison Break', 'Peaky Blinders', 'The Sopranos', 'Squid Game', 'Better Call Saul', 'Money Heist', 'The Boys', 'Succession', 'The Last of Us', 'Ted Lasso', 'Sherlock', 'Dark', 'Severance', 'The Bear', 'Suits']),
    sub('screen-movies', 'Movies', 'Only film you can watch', ['The Dark Knight', 'Inception', 'Interstellar', 'Oppenheimer', 'The Godfather', 'Pulp Fiction', 'Avengers: Endgame', 'Titanic', 'Gladiator', 'Fight Club', 'The Matrix', 'Forrest Gump', 'Shawshank Redemption', 'Spirited Away', 'Dune', 'Parasite', 'Top Gun: Maverick', 'Joker', 'Toy Story', 'The Lion King']),
    sub('screen-marvel', 'Marvel Heroes', 'Suit up as one', ['Iron Man', 'Spider-Man', 'Captain America', 'Thor', 'Hulk', 'Black Panther', 'Doctor Strange', 'Wolverine', 'Deadpool', 'Black Widow', 'Scarlet Witch', 'Star-Lord', 'Ant-Man', 'Captain Marvel', 'Hawkeye', 'Loki', 'Vision', 'Daredevil', 'Thanos', 'Silver Surfer']),
    sub('screen-starwars', 'Star Wars', 'Characters and ships', ['Darth Vader', 'Luke Skywalker', 'Yoda', 'Obi-Wan Kenobi', 'The Mandalorian', 'Grogu', 'Han Solo', 'Anakin Skywalker', 'Darth Maul', 'Kylo Ren', 'Ahsoka Tano', 'Boba Fett', 'Chewbacca', 'R2-D2', 'Millennium Falcon', 'X-wing', 'Death Star', 'Lightsaber (any color)']),
    sub('screen-directors', 'Directors', 'They make your life story', ['Christopher Nolan', 'Quentin Tarantino', 'Steven Spielberg', 'Martin Scorsese', 'Denis Villeneuve', 'James Cameron', 'Ridley Scott', 'Hayao Miyazaki', 'Guy Ritchie', 'Wes Anderson', 'Peter Jackson', 'Greta Gerwig', 'Bong Joon-ho', 'David Fincher', 'Jordan Peele', 'George Lucas']),
  ]),
  cat('music', 'Music', 'Artists, albums, concerts', '#C77DFF', [
    sub('music-artists', 'Artists', 'Only artist you can listen to', ['Drake', 'Taylor Swift', 'The Weeknd', 'Kendrick Lamar', 'Travis Scott', 'Bad Bunny', 'Billie Eilish', 'Ed Sheeran', 'Eminem', 'Kanye West', 'Beyoncé', 'Rihanna', 'Bruno Mars', 'SZA', 'Post Malone', 'Frank Ocean', 'Adele', 'Dua Lipa', 'Coldplay', 'J. Cole']),
    sub('music-arabic', 'Arabic Artists', 'Khaleeji and beyond', ['Mohammed Abdu', 'Talal Maddah', 'Rashed Al-Majed', 'Abdul Majeed Abdullah', 'Amr Diab', 'Umm Kulthum', 'Fairuz', 'Hussain Al Jassmi', 'Nancy Ajram', 'Ahlam', 'Balqees', 'Tamer Hosny', 'Wegz', 'Saint Levant', 'Abu', 'Majed Al Mohandes', 'Fahad Al Kubaisi', 'Ayed', 'Assala', 'Elissa']),
    sub('music-kpop', 'K-pop', 'One group, every comeback', ['BTS', 'BLACKPINK', 'Stray Kids', 'NewJeans', 'SEVENTEEN', 'TWICE', 'aespa', 'IVE', 'LE SSERAFIM', 'ENHYPEN', 'TXT', 'ATEEZ', 'NCT', 'EXO', 'BIGBANG', 'Red Velvet', 'ITZY', 'BABYMONSTER', 'RIIZE', 'Jungkook solo']),
    sub('music-albums', 'Albums', 'One album on repeat', ['Thriller', 'To Pimp a Butterfly', 'Blonde', 'Abbey Road', 'The Dark Side of the Moon', 'Take Care', 'After Hours', 'Astroworld', 'good kid, m.A.A.d city', '1989', 'My Beautiful Dark Twisted Fantasy', 'Nevermind', '21', 'Back to Black', 'Un Verano Sin Ti', 'Channel Orange', 'Rumours', 'Graduation']),
    sub('music-concerts', 'Concerts', 'Front row, any era', ['Michael Jackson 1992', 'Queen at Live Aid', 'Eminem 2002', 'The Weeknd After Hours tour', 'Travis Scott Astroworld', 'Beyoncé Renaissance', 'Taylor Swift Eras', 'Coldplay Music of the Spheres', 'Kendrick Lamar 2024', 'Drake & 21 Savage', 'Bad Bunny 2024', 'Ed Sheeran Mathematics', 'Daft Punk 2007', 'Adele Vegas', 'Bruno Mars Riyadh', 'Rihanna Super Bowl']),
  ]),
  cat('tech', 'Tech', 'Gadgets and brands', '#7FB4FF', [
    sub('tech-phones', 'Phones', 'Your only phone for 5 years', ['iPhone 17 Pro Max', 'Samsung Galaxy S25 Ultra', 'Google Pixel 10 Pro', 'Samsung Galaxy Z Fold 7', 'iPhone 17', 'OnePlus 13', 'Xiaomi 15 Ultra', 'iPhone SE', 'Nothing Phone 3', 'Huawei Pura', 'Samsung Galaxy Z Flip 7', 'iPhone 6 (2014)', 'Nokia 3310', 'BlackBerry Bold', 'Motorola Razr', 'Sony Xperia']),
    sub('tech-gadgets', 'Gadgets', 'One gadget, free forever', ['MacBook Pro', 'iPad Pro', 'Apple Watch Ultra', 'AirPods Pro', 'PS5 Pro', 'Steam Deck', 'Meta Quest 3', 'Apple Vision Pro', 'Kindle', 'GoPro', 'DJI Drone', 'Sony WH-1000XM6', 'Nintendo Switch 2', 'Dyson Airwrap', 'Roomba', 'Tesla Powerwall', 'Garmin Fenix', 'Ray-Ban Meta']),
    sub('tech-brands', 'Tech Brands', 'Lifetime supply from one', ['Apple', 'Samsung', 'Google', 'Microsoft', 'Sony', 'Nintendo', 'Tesla', 'Nvidia', 'Amazon', 'Netflix', 'Spotify', 'Meta', 'OpenAI', 'Anthropic', 'TikTok', 'Snapchat', 'Xiaomi', 'Dyson']),
    sub('tech-ai', 'AI Tools', 'One assistant, forever', ['ChatGPT', 'Claude', 'Gemini', 'Midjourney', 'Copilot', 'Perplexity', 'Grok', 'Cursor', 'Sora', 'ElevenLabs', 'Notion AI', 'DeepSeek', 'Runway', 'Suno', 'Character.AI', 'Siri', 'Alexa', 'Google Translate']),
    sub('tech-apps', 'Apps', 'Only app on your phone', ['Instagram', 'TikTok', 'YouTube', 'WhatsApp', 'Snapchat', 'X', 'Spotify', 'Netflix', 'Google Maps', 'ChatGPT', 'Telegram', 'Discord', 'Reddit', 'Twitch', 'Uber', 'HungerStation', 'Jahez', 'Absher', 'Noon', 'Shein']),
  ]),
  cat('style', 'Style', 'Sneakers, watches, scents, brands', '#F2C14E', [
    sub('style-sneakers', 'Sneakers', 'One pair, on feet forever', ['Air Jordan 1', 'Air Jordan 4', 'Nike Dunk Low', 'Nike Air Force 1', 'Yeezy 350', 'Yeezy Slide', 'New Balance 550', 'New Balance 990', 'Adidas Samba', 'Adidas Gazelle', 'Nike Air Max 1', 'Nike Air Max 97', 'Travis Scott Jordan 1 Low', 'Off-White Jordan 1', 'Balenciaga Triple S', 'Converse Chuck 70', 'Salomon XT-6', 'Asics Gel-Kayano 14', 'Onitsuka Tiger Mexico 66', 'Nike Vomero 5']),
    sub('style-watches', 'Watches', 'One wrist, one watch', ['Rolex Submariner', 'Rolex Daytona', 'Rolex Datejust', 'Audemars Piguet Royal Oak', 'Patek Philippe Nautilus', 'Richard Mille RM 011', 'Omega Speedmaster', 'Omega Seamaster', 'Cartier Santos', 'Cartier Tank', 'Tudor Black Bay', 'Casio G-Shock', 'Apple Watch Ultra', 'TAG Heuer Carrera', 'Hublot Big Bang', 'Grand Seiko Snowflake', 'IWC Pilot', 'Breitling Navitimer', 'Vacheron Constantin Overseas', 'Casio F-91W']),
    sub('style-perfumes', 'Perfumes', 'Signature scent for life', ['Dior Sauvage', 'Creed Aventus', 'Bleu de Chanel', 'Tom Ford Oud Wood', 'YSL Y', 'Baccarat Rouge 540', 'Versace Eros', 'Acqua di Giò', 'Le Labo Santal 33', 'Jean Paul Gaultier Le Male', 'Parfums de Marly Layton', 'Xerjoff Naxos', 'Initio Oud for Greatness', 'Lattafa Khamrah', 'Ajmal Amber Wood', 'Abdul Samad Al Qurashi Oud', 'Arabian Oud Kalemat', 'Tom Ford Tobacco Vanille', 'Chanel No. 5', 'Dior Homme Intense']),
    sub('style-brands', 'Luxury Brands', 'Free wardrobe from one house', ['Louis Vuitton', 'Gucci', 'Dior', 'Chanel', 'Hermès', 'Prada', 'Balenciaga', 'Versace', 'Burberry', 'Fendi', 'Bottega Veneta', 'Saint Laurent', 'Off-White', 'Supreme', 'Ralph Lauren', 'Zara', 'Nike', 'Adidas', 'Loro Piana', 'Amiri']),
    sub('style-eid', 'Eid Essentials', 'The fit, sorted', ['New white thobe', 'Red shemagh', 'White ghutra', 'Bisht', 'Oud bottle', 'Bukhoor', 'Gold cufflinks', 'Fresh na\'al sandals', 'Eidiyah stack', 'A haircut the night before', 'Tailored vest', 'Prayer beads', 'Ma\'amoul box', 'Saudi coffee set', 'Perfume layering kit', 'Ironed ghutra fold']),
  ]),
  cat('life', 'Life & Fun', 'Superpowers, pets, upgrades', '#4FE0C0', [
    sub('life-superpowers', 'Superpowers', 'Only one power', ['Flight', 'Invisibility', 'Teleportation', 'Time travel', 'Mind reading', 'Super strength', 'Super speed', 'Healing', 'Immortality', 'Shape-shifting', 'Telekinesis', 'Control fire', 'Control weather', 'Talk to animals', 'Photographic memory', 'Stop time', 'Invulnerability', 'X-ray vision', 'Infinite money glitch', 'Never need sleep']),
    sub('life-pets', 'Pets', 'One pet, no allergies', ['Golden Retriever', 'Husky', 'German Shepherd', 'Persian Cat', 'Scottish Fold', 'Falcon', 'Arabian Horse', 'Camel', 'Parrot', 'Bengal Cat', 'Corgi', 'Bulldog', 'Pomeranian', 'Turtle', 'Hamster', 'Saluki', 'Rabbit', 'Koi Pond', 'Axolotl', 'Monkey']),
    sub('life-upgrades', 'Life Upgrades', 'One upgrade, permanent', ['Never traffic again', 'Perfect sleep', 'Free flights forever', 'Fluent in every language', 'Photographic memory', 'Never get sick', 'Unlimited coffee', 'A personal chef', 'A private driver', 'Four-day work week', 'Perfect eyesight', 'Never wait in line', 'Instant tan', 'Always on time', 'Perfect handwriting', 'Free internet everywhere', 'Endless PTO', 'Never lose your keys']),
    sub('life-jobs', 'Dream Jobs', 'Start Monday', ['Pro footballer', 'F1 driver', 'Pilot', 'Astronaut', 'Actor', 'YouTuber', 'Surgeon', 'Game developer', 'Architect', 'Chef', 'DJ', 'Travel blogger', 'Fashion designer', 'Race engineer', 'Photographer', 'Startup founder', 'Voice actor', 'Marine biologist']),
    sub('life-houses', 'Dream Homes', 'Move in tomorrow', ['Beach villa in Jeddah', 'Penthouse in Dubai', 'Farm in AlUla', 'Chalet in Switzerland', 'Loft in New York', 'Riad in Marrakech', 'Villa in Bali', 'Apartment in Tokyo', 'Townhouse in London', 'Cabin in Norway', 'Ranch in Texas', 'Istiraha in Riyadh', 'Yacht (that\'s the house)', 'Castle in Scotland', 'Treehouse in Costa Rica', 'Desert camp in the Empty Quarter']),
  ]),
  cat('creators', 'Creators', 'YouTubers and streamers', '#FF6B6B', [
    sub('creators-youtube', 'YouTubers', 'Collab with one', ['MrBeast', 'PewDiePie', 'Mark Rober', 'Dude Perfect', 'Marques Brownlee', 'Casey Neistat', 'Sidemen', 'KSI', 'Logan Paul', 'Ryan Trahan', 'Jacksepticeye', 'Markiplier', 'Airrack', 'Danny Duncan', 'Unspeakable', 'SSSniperWolf', 'Emma Chamberlain', 'Michelle Khare', 'Ludwig', 'Veritasium']),
    sub('creators-streamers', 'Streamers', 'Duo queue for life', ['IShowSpeed', 'Kai Cenat', 'xQc', 'Ninja', 'Pokimane', 'Shroud', 'TimTheTatman', 'Dream', 'Tfue', 'Valkyrae', 'Sykkuno', 'Tarik', 'Agent 00', 'Jynxzi', 'Clix', 'Adin Ross', 'Sketch', 'Caseoh', 'HasanAbi', 'Amouranth']),
  ]),
  cat('gulf', 'Khaleeji Life', 'For the ones who get it', '#E3B23C', [
    sub('gulf-shows', 'Ramadan Series', 'Only one every year', ['Tash Ma Tash', 'Bab Al Hara', 'Selfie', 'Al Asouf', 'Sikkat Safar', 'Khalid bin Al Waleed', 'Omar', 'Bini w Bink', 'Zawaj Maslaha', 'Rashash', 'Al Kabeer Awi', 'Ramez', 'Grand Hotel', 'Al Mirath', 'Al Dawla', 'Kaser Al Basha']),
    sub('gulf-games', 'Card & Board Games', 'The majlis classic', ['Baloot', 'Jackaroo', 'Kout Bo 6', 'Sequence', 'Carrom', 'Uno', 'Monopoly', 'Ludo', 'Dominoes', 'Trix', 'Hand', 'Tarneeb', 'Chess', 'Backgammon', 'Skip-Bo', 'Rummikub']),
    sub('gulf-gatherings', 'Gatherings', 'Your weekend, always', ['Istiraha', 'Kashta in the desert', 'Beach day', 'Majlis and karak', 'Eid morning', 'Shisha lounge', 'Football at the sports club', 'Chalet weekend', 'Mall walk', 'Cinema night', 'Kaboos and tea', 'PlayStation night', 'Qahwa at grandma\'s', 'Farm barbecue', 'Boulevard walk', 'Road trip to Dubai']),
    sub('gulf-street-food', 'Gulf Street Food', 'From the cart', ['Shawarma', 'Falafel sandwich', 'Broast', 'Karak', 'Mutabbaq', 'Samboosa', 'Foul and tamees', 'Chapati and cheese', 'Corn in a cup', 'Kunafa', 'Luqaimat', 'Zinger', 'Balaleet', 'Regag bread', 'Haneeth', 'Dango']),
    sub('gulf-slang', 'Slang Only We Get', 'Bid on the vibe', ['Yalla', 'Inshallah (meaning no)', 'Wallah', 'Habibi', 'Shloonak', 'Khalas', 'Aywa', 'Bas', 'Zain', 'Wain', 'Ya3ni', 'Tayeb', 'Ayb', 'Eshtoo', 'Hala wallah', 'Allah yaslmk', 'Yuba', 'Shakhbari', 'Ma alaih', 'Tawwa']),
  ]),
];

export const COMING_SOON: string[] = ['Cricket', 'Motorbikes', 'Camping Gear', 'Board Games', 'Startups', 'Saudi Creators'];
